apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: h200-ccc
spec:
  activeMigration:
    optimizeRulePriority: false
  priorities:
  - machineType: a3-ultragpu-8g
    storage:
      localSSDCount: 32
  - nodepools: ['h200-ccc']
  - gpu:
      type: "nvidia-h200-141gb"
      count: 1
      driverVersion: "latest"
  - flexStart:
      enabled: true