
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen3-235b-a22b-vllm-h100
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen3-235b-a22b-vllm-h100
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/cpu-limit: "0"
        gke-gcsfuse/memory-limit: "0"
        gke-gcsfuse/ephemeral-storage-limit: "0"
      labels:
        app: qwen3-235b-a22b-vllm-h100
    spec:
      serviceAccountName: "gke-ksa"
      nodeSelector:
        cloud.google.com/compute-class: "h100-ccc"
      containers:
      - name: inference-server
        image: vllm/vllm-openai:v0.10.0
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: hf_api_token
        - name: LD_LIBRARY_PATH
          value: /usr/local/nvidia/lib64:/usr/local/cuda/lib64:\$LD_LIBRARY_PATH
        - name: PATH
          value: /usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:\$PATH
        command:
          - sh
          - -c
          - "vllm serve /bucket/models/Qwen3-235B-A22B-Thinking-2507 --port 8080 --disable-log-requests --seed 42 --max-model-len 32768 --gpu-memory-utilization 0.95 --tensor-parallel-size 8"
        resources:
          limits:
            nvidia.com/gpu: "8"
          requests:
            nvidia.com/gpu: "8"
        ports:
          - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - name: gcs-fuse-csi-eph
            mountPath: /bucket
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: gcs-fuse-csi-eph
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: ikwak-stuff
            gcsfuseMetadataPrefetchOnMount: "true"
            mountOptions: "implicit-dirs,file-mode=777,dir-mode=777,file-cache:enable-parallel-downloads:true,file-cache:cache-file-for-range-read:true,file-cache:max-size-mb:-1,write:enable-streaming-writes:true,read_ahead_kb=1024,file-system:kernel-list-cache-ttl-secs:-1"
---
apiVersion: v1
kind: Service
metadata:
  name: qwen3-235b-a22b-llm-service
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: qwen3-235b-a22b-vllm-h100
  type: ClusterIP
